language: java
jdk: oraclejdk7
before_script:
  - git remote add upstream https://github.com/wso2/product-greg
  - git fetch upstream
  - git checkout master
  - git rebase upstream/master
script: mvn -s ./settings.xml clean install -Dmaven.test.skip=true -B -U
